myproject/core/urls.py
from django.urls import path

from myproject.core import views as v

app_name = 'core'


urlpatterns = [
    path('', v.index, name='index'),
    path('task/print_numbers/', v.run_task, name='run_task'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('myproject.core.urls')),
    path('admin/', admin.site.urls),
]

myproject/core/models.py
from django.db import models

# Create your models here.

myproject/core/views.py
from decouple import config
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django_celery_results.models import TaskResult

from .tasks import print_numbers


def index(request):
    template_name = 'index.html'
    object_list = TaskResult.objects.all()
    my_key = config('KEY')
    context = {'object_list': object_list, 'my_key': my_key}
    return render(request, template_name, context)


def run_task(request):
    print_numbers.delay(10)
    url = 'core:index'
    return HttpResponseRedirect(reverse(url))

myproject/core/templates/base.html
<!-- https://getbootstrap.com/docs/4.0/getting-started/introduction/#starter-template -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">
  <!-- <link rel="shortcut icon" href="http://html5-training-in-hyderabad.blogspot.com.br/favicon.ico"> -->
  <title>Celery on Docker</title>
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <!-- Font-awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  <style>
    body {
      margin-top: 60px;
    }
  </style>

  {% block css %}{% endblock css %}

  </body>
</head>
<body>

  {% include "includes/nav.html" %}

  <div class="container">
    {% block content %}{% endblock content %}
  </div>

  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

  <script src="https://js.pusher.com/4.4/pusher.min.js"></script>

  <!-- bootstrap-notify -->
  <!-- http://bootstrap-notify.remabledesigns.com/ -->
  <script src="{% static 'js/bootstrap-notify.min.js' %}"></script>

  {% block js %}{% endblock js %}

</body>
</html>

myproject/core/templates/includes/nav.html
<!-- https://getbootstrap.com/docs/4.0/examples/starter-template/ -->
<!-- https://github.com/JTruax/bootstrap-starter-template/blob/master/template/start.html -->

<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="{% url 'core:index' %}">Celery com Docker</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'core:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
        </ul>
    </div>
</nav>

myproject/core/templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="jumbotron">
  <div class="container">
    <h1>Teste Django e Celery no Docker com Redis</h1>
    <p>
      <button id="id_btn" class="btn btn-primary btn-lg" type="button">
        Clique aqui
      </button>
    </p>
  </div>
</div>

<div class="text-center mt-5 pt-5">
    <h1>Task Results</h1>
    <table class="table">
      <thead>
        <tr>
          <th>Task ID</th>
          <th>Task Name</th>
          <th>Completed Datetime</th>
          <th>Task State</th>
        </tr>
      </thead>
      <tbody>
        {% for object in object_list %}
          <tr>
            <td>{{ object.task_id }}</td>
            <td>{{ object.task_name }}</td>
            <td>{{ object.date_done }}</td>
            <td>{{ object.status }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
</div>

{% endblock content %}

{% block js %}

  <script>

    $('#id_btn').on('click', function() {
      let url = "{% url 'core:run_task' %}";
      $.ajax({
        url: url,
        beforeSend: function(xhr) {
          myNotifyWarning('iniciada...')
        },
        success: function(response) {
        }
      })
    });

    function myNotifyWarning(message) {
      $.notify({
        title: "<strong>Tarefa:</strong> ",
        message: message
      },{
        type: "warning",
        delay: 3000,
        timer: 1000,
      });
    }

    function myNotifySuccess(message) {
      $.notify({
        title: "<strong>Tarefa:</strong> ",
        message: message
      },{
        delay: 3000,
        timer: 1000,
      });
    }

    function reload() {
      setTimeout(function() {
        location.reload();
    }, 3200);
    }

    // Enable pusher logging - don't include this in production
    Pusher.logToConsole = true;

    var my_key = '{{ my_key }}'
    var pusher = new Pusher(my_key, {
      cluster: 'mt1',
      forceTLS: true
    });

    var channel = pusher.subscribe('my-channel');
    channel.bind('my-event', function(data) {
      myNotifySuccess(data.message);
      reload()
    });
  </script>

{% endblock js %}